outpath: output/

gurobi:
    license: ~/gurobi.lic
    timeout: 1

exec:
    split: py/freddie_split.py
    segment: py/freddie_segment.py
    cluster: py/freddie_cluster.py
    isoforms: py/freddie_isoforms.py

samples:
    S1:
        ref: Homo_sapiens_chr21
        bc_wl: 10x
        reads: output/simulate/TS/S1.fastq
        truth: output/simulate/TS/S1.tsv
    # N1:
    #     ref: Homo_sapiens
    #     reads: data/samples/N1.fastq
    #     truth: output/simulate/TS/S1.tsv

refs:
    Homo_sapiens:
        GTF : data/refs/homo_sapiens.annot.gtf
        DNA : data/refs/homo_sapiens.dna.fa
        cDNA : data/refs/homo_sapiens.cdna.fa
    Homo_sapiens_chr21:
        GTF: data/refs/homo_sapiens.chr21.annot.gtf
        DNA: data/refs/homo_sapiens.chr21.dna.fa
        cDNA: data/refs/homo_sapiens.chr21.cdna.fa
    barcodes:
        10x: data/refs/3M-february-2018.txt.gz
