name: freddie_dev
channels:
  - conda-forge
  - bioconda
  - nodefaults
  - anaconda
  - gurobi
dependencies:
  - gurobi==9.*
  - networkx>=2
  - numpy>=1.16
  - pysam>=0.15
  - python>=3.8
  - scikit-learn>=0.20
  - scipy>=1.2.1
  - snakemake>=7.0.0
  - tqdm
  - cgranges
