outpath: output/simulate
enable_piping: false
# Pipeline modules

TS_experiments:
    C1:
        pipeline:
            - Tsb:
                  params: "--molecule-count 50000 --molecule-prefix C1: -s 41"
                  model: A549
    C2:
        pipeline:
            - Tsb:
                  params: "--molecule-count 50000 --molecule-prefix C2: -s 42"
                  model: Hct116
    C3:
        pipeline:
            - Tsb:
                  params: "--molecule-count 50000 --molecule-prefix C3: -s 43"
                  model: HepG2
    C4:
        pipeline:
            - Tsb:
                  params: "--molecule-count 50000 --molecule-prefix C4: -s 44"
                  model: K562
    C5:
        pipeline:
            - Tsb:
                  params: "--molecule-count 50000 --molecule-prefix C5: -s 45"
                  model: MCF7
    S1_p1:
        pipeline:
            - Mrg:
                  sources: ["C1", "C2", "C3", "C4", "C5"]
            - Flt:
                  params: '-c "info CB"'
            - plA:
                  params: "--normal=15,7.5"
            - Tag:
                  params: "--format3 10"
            - SCB:
                  params: ""
            - Tag:
                  params: "--format3 AGATCGGAAGAGCGTCGTGTAG"
    S1_p2:
        pipeline:
            - Mrg:
                  sources: ["C1", "C2", "C3", "C4", "C5"]
            - Flt:
                  params: '-c "info CB" --negate'
    S1:
        pipeline:
            - Mrg:
                  sources: ["S1_p1", "S1_p2"]
            - PCR:
                  params: "--cycles 5 --molecule-count 100000 --error-rate 0.0 --efficiency 0.88"
            - Flp:
                  params: "-p 0.5"
            - Tag:
                  params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
            - Trc:
                  params: ""
                  model: MCF7
            - Shf:
                  params: ""
            - Seq:
                  params: "--skip-qual-compute"

exec:
    tksm: bin/tksm

refs:
    Homo_sapiens:
        GTF: data/refs/homo_sapiens.annot.gtf
        DNA: data/refs/homo_sapiens.dna.fa
        cDNA: data/refs/homo_sapiens.cdna.fa
    Homo_sapiens_chr21:
        GTF: data/refs/homo_sapiens.chr21.annot.gtf
        DNA: data/refs/homo_sapiens.chr21.dna.fa
        cDNA: data/refs/homo_sapiens.chr21.cdna.fa
    barcodes:
        10x: data/refs/3M-february-2018.txt.gz

samples:
    A549:
        fastq:
            - data/samples/SGNex_A549_directcDNA_replicate1_run3.fastq.gz
        ref: Homo_sapiens_chr21
    Hct116:
        fastq:
            - data/samples/SGNex_Hct116_directcDNA_replicate4_run1.fastq.gz
        ref: Homo_sapiens_chr21
    HepG2:
        fastq:
            - data/samples/SGNex_HepG2_directcDNA_replicate5_run3.fastq.gz
        ref: Homo_sapiens_chr21
    K562:
        fastq:
            - data/samples/SGNex_K562_directcDNA_replicate1_run2.fastq.gz
        ref: Homo_sapiens_chr21
    MCF7:
        fastq:
            - data/samples/SGNex_MCF7_directcDNA_replicate4_run2.fastq.gz
        ref: Homo_sapiens_chr21

models:
    Tsb:
        A549:
            sample: A549
            cb-txt: 10x
            params: "--cb-count 500 --random-seed 41"
        Hct116:
            sample: Hct116
            cb-txt: 10x
            params: "--cb-count 500 --random-seed 42"
        HepG2:
            sample: HepG2
            cb-txt: 10x
            params: "--cb-count 500 --random-seed 43"
        K562:
            sample: K562
            cb-txt: 10x
            params: "--cb-count 500 --random-seed 44"
        MCF7:
            sample: MCF7
            cb-txt: 10x
            params: "--cb-count 500 --random-seed 45"
